export const dummy = [
    {
      k:"1",
      to:"Alita kyler",
      rp:"0705006856",
      usd:"505",
      kes:"56800",
      dt:"Nov 29 20",
    },
    {
      k:"2",
      to:"KPLC Post-paid Account",
      rp:"888888",
      usd:"35",
      kes:"425",
      dt:"Nov 27 20",
    },
    {
      k:"3",
      to:"Quickmat Supermarkets",
      rp:"560777",
      usd:"65",
      kes:"6950",
      dt:"Nov 026 20",
    },
    {
      k:"4",
      to:"Irine Kina",
      rp:"0748077438",
      usd:"10",
      kes:"1085",
      dt:"Nov 15 20",
    },
    {
      k:"5",
      to:"Gregory Water Supplies",
      rp:"225667",
      usd:"505",
      kes:"56800",
      dt:"Nov 05 20",
    },
    {
      k:"6",
      to:"Alita kyler",
      rp:"0705006856",
      usd:"505",
      kes:"56800",
      dt:"Nov 29 20",
    },
    {
      k:"7",
      to:"KPLC Post-paid Account",
      rp:"888888",
      usd:"35",
      kes:"425",
      dt:"Nov 27 20",
    },
    {
      k:"8",
      to:"Quickmat Supermarkets",
      rp:"560777",
      usd:"65",
      kes:"6950",
      dt:"Nov 026 20",
    },
    {
      k:"9",
      to:"Irine Kina",
      rp:"0748077438",
      usd:"10",
      kes:"1085",
      dt:"Nov 15 20",
    },
    {
      k:"10",
      to:"Gregory Water Supplies",
      rp:"225667",
      usd:"505",
      kes:"56800",
      dt:"Nov 05 20",
    },
    {
      k:"11",
      to:"Alita kyler",
      rp:"0705006856",
      usd:"505",
      kes:"56800",
      dt:"Nov 29 20",
    },
    {
      k:"12",
      to:"KPLC Post-paid Account",
      rp:"888888",
      usd:"35",
      kes:"425",
      dt:"Nov 27 20",
    },
    {
      k:"13",
      to:"Quickmat Supermarkets",
      rp:"560777",
      usd:"65",
      kes:"6950",
      dt:"Nov 026 20",
    },
    {
      k:"14",
      to:"Irine Kina",
      rp:"0748077438",
      usd:"10",
      kes:"1085",
      dt:"Nov 15 20",
    },
    {
      k:"15",
      to:"Gregory Water Supplies",
      rp:"225667",
      usd:"505",
      kes:"56800",
      dt:"Nov 05 20",
    }
  ];

  export const faq = [
    {
      k:"1",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"2",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"3",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"4",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"5",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"6",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"7",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"8",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"9",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"10",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"11",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"12",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"13",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"14",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    },
    {
      k:"15",
      q:"How is my personal information protected?",
      a:"All data is encrypted using AES-256 algorithm to ensure no one can break it. Our App runs on a secure server managed by Google",
    }
  ];